### ISSUE TITLE
The PHPStan Language Server server crashed 5 times since 3.2.2

### ISSUE THREAD

**Issue by petski** [SanderRonde/phpstan-vscode#102]
![image](https://github.com/user-attachments/assets/da30f355-5d2f-43ff-921c-b04df2cda7bb)

Reverting to version 3.1.14 seems to be a workaround for now.

Relevant log:

```
[9/8/2024, 10:10:15 PM] [server] Language server ready
[9/8/2024, 10:10:15 PM] [file-watcher] Checking: New document active active
[9/8/2024, 10:10:15 PM] [check:1] Check started for project
[9/8/2024, 10:10:15 PM] [server] PHPStan version: PHPStan - PHP Static Analysis Tool 1.12.x-dev@

[9/8/2024, 10:10:15 PM] [check:1] Spawning PHPStan with the following configuration:  {"binStr":"/var/www/vendor/bin/phpstan","args":["analyse","-c","/var/www/phpstan.dist.neon","--error-format=json","--no-interaction","--memory-limit=1G"]}
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}

Node.js v20.15.1
[Info  - 10:10:15 PM] Connection to server got closed. Server will restart.
true
```

**Comment by SanderRonde** [comment]
Thanks for the report! Should be fixed in the latest release (`3.2.3`). I have a hunch what it was but given that I can't reproduce it didn't completely verify that it was fixed. Can you let me know if it's fixed?

And if it's not fixed, can you share with me your OS and setup? It looks like the `ps` command is not defined, if I could replicate your setup I can more easily debug it.

**Comment by petski** [comment]
Unfortunately, the issue remains, exactly same error message.

My setup is:
- Ubuntu Linux 24.04
- VSCode 1.93.0
- My project is in a docker container, which is based on the official `php:8.3` docker image
- I use the "Dev Container" feature of VSCode to work "inside" the container

The command `ps` indeed isn't available in the container:

```
$ docker run -i -t --rm php:8.3 ls -l /usr/bin/ps
ls: cannot access '/usr/bin/ps': No such file or directory
```

(It's not in another PATH too, I double-checked)

Strangely, the error is also shown when I set `phpstan.enableLanguageServer` to `false`.

FWIW, I also have the `intelephense` extension running a language server.

**Comment by SanderRonde** [comment]
Thanks for the info! I've managed to replicate it and actually fix it this time. Check out version `3.2.4`.

Regarding the `phpstan.enableLanguageServer` comment. The `enableLanguageServer` setting doesn't actually control whether the language server itself is enabled but whether on-hover information is enabled. The naming is indeed quite bad but VSCode doesn't allow for a proper way to rename config options without breaking existing configs so I'm kind of stuck with it.

**Comment by petski** [comment]
Can confirm the crash error-messages have disappeared with `3.2.4`. Thanks!

Bit out of scope for this ticket, but just two small FYI's/FWIW's regarding `enableLanguageServer`:
- You could implement the feature under another config variable **TOO**, and [leverage the `deprecationMessage` feature VSCOde has](https://github.com/microsoft/vscode-discussions/discussions/862).
- The `enableLanguageServer` "overlaps/collides" with the very nice [`intelephense.compatibility.preferPsalmPhpstanPrefixedAnnotations`-feature](https://github.com/bmewburn/vscode-intelephense/issues/2128#issuecomment-2334917789).

**Comment by SanderRonde** [comment]
Thanks! Indeed better to do that, I'll rename it to `showTypeOnHover` but keep supporting the old field
