### ISSUE TITLE
Make this more prominent or default option

### ISSUE THREAD

**Issue by markovicdenis** [SanderRonde/phpstan-vscode#108]
It took me so loong to figure out why this extension crashes, most people just end up switching to the other phpstan vscode version. I would suggest to make this the default, since nobody actually doesn't use xcode when doing PHP development and the FAQ below gets probably skipped by 90%.

```json
  "phpstan.ignoreErrors": ["Xdebug: .*"]
```

**Comment by SanderRonde** [comment]
Good point, will do that :)
