### ISSUE TITLE
errors shows in the output but not in the editor or problems panel

### ISSUE THREAD

**Issue by ctf0** [SanderRonde/phpstan-vscode#113]
- trmnl
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/29b6b257-849e-45a6-817a-862344406ec2">

- output
<img width="574" alt="image" src="https://github.com/user-attachments/assets/8feb0e18-9494-42e3-b42a-be6df672f3e4">

however the extension always display an error at the end of the analyze
```
PHPStan: process exited with error, see log for details
```

and here is the output
```
[12/4/2024, 8:28:52 PM] [status-bar] Hiding status bar, last operation result = Error
[12/4/2024, 8:28:52 PM] [check:1] Check completed for file, errors= {"fileSpecificErrors":{},"notFileSpecificErrors":[]}
```

sadly am also using a bit of an old version of phpstan `v0.12.99`,however am not sure if there is something am missing to get it to display the results in the editor.

**Comment by SanderRonde** [comment]
It could indeed be because of the old version. Are there any other errors being shown in the log? I get a lot of "deprecated" errors, which are causing the extension to think that something has gone wrong. Is it the same for you or is this all you see?

**Comment by ctf0** [comment]
sorry for the delay, yes same here as well

**Comment by SanderRonde** [comment]
Ah alright that explains it then. You should be able to ignore those warnings by using the `phpstan.ignoreErrors` setting, which takes an array of regexes. Let me know if that helps

**Comment by ctf0** [comment]
thank you for ur help but currently its unusable and the error msgs are too many, when running the cmnd

```
phpstan analyze -c phpstan.neon --error-format=json --no-interaction --no-progress path/to/file.php
```

at some point i get

```
⚠️  You're running a really old version of PHPStan.️

The last release in the 0.12.x series with new features
and bugfixes was released on September 12th 2021,
that's 1190 days ago.

Since then more than 67 new PHPStan versions were released
with hundreds of new features, bugfixes, and other
quality of life improvements.

To learn about what you're missing out on, check out
this blog with articles about the latest major releases:
https://phpstan.org/blog

Upgrade today to PHPStan 1.8 or newer by using
"phpstan/phpstan": "^1.8" in your composer.json.
```

then more deprecation text & the last line is
```
{"totals":{"errors":0,"file_errors":0},"files":[],"errors":[]}%                                
```

**Comment by SanderRonde** [comment]
Hmm I guess you could always try ignoring `.*` and just ignore everything. If that doesn't work then maybe it's just not possible :(

**Comment by ctf0** [comment]
unfortunately the deprecation errors are unskippable, still thank you so much for your help.
