### ISSUE TITLE
I use docker. How can I make this plug-in work properly

### ISSUE THREAD

**Issue by 645418484** [SanderRonde/phpstan-vscode#12]
My OS is Windows11 And  PHP and Composer Working in docker,
I edited a bat script to call the CLI instruction of docker in the system
Now, the problem I'm facing is that the plug-in will be automatically invoked and the file will be automatically loaded. I don't know how to configure it
![image](https://user-images.githubusercontent.com/38717760/184157037-243dfba2-61e8-4226-a2a5-88f271266c59.png)

**Comment by 645418484** [comment]
Now I can run the script in cli
![image](https://user-images.githubusercontent.com/38717760/184159593-bfceb89d-57a9-44fe-8824-bebbc07176b7.png)

**Comment by SanderRonde** [comment]
Ah I see what the error is. I've added a setting called `enableLanguageServer` that allows for you to turn off the feature that causes this bug. Could you try out the build of the extension I attached? It contains the new change. When you've installed it, just disable the `enableLanguageServer` setting and try again.

(Github doesn't allow attaching `.vsix` files so I've renamed it to `.zip`, just rename it back to `.vsix` and drag it into your "extensions" panel)
[phpstan-vscode-2.2.7.zip](https://github.com/SanderRonde/phpstan-vscode/files/9329959/phpstan-vscode-2.2.7.zip)

**Comment by 645418484** [comment]
> 啊，我看到错误是什么。我添加了一个名为的设置，允许您关闭导致此错误的功能。你能试试我附加的扩展的构建吗？它包含新的更改。安装完成后，只需禁用该设置，然后重试即可。`enableLanguageServer``enableLanguageServer`
> 
> （Github不允许附加文件，所以我已将其重命名为，只需将其重命名回并将其拖到“扩展”面板中即可） [phpstan-vscode-2.2.7.zip](https://github.com/SanderRonde/phpstan-vscode/files/9329959/phpstan-vscode-2.2.7.zip)`.vsix``.zip``.vsix`
Sorry, I just saw it now
OK, I'll try it

**Comment by 645418484** [comment]
emmm  Look, he can't find the autoload file now
![image](https://user-images.githubusercontent.com/38717760/185601091-438319dd-b004-4180-aecd-0ae6b219100d.png)

**Comment by SanderRonde** [comment]
Are you sure you set the `phpstan.enableLanguageServer` setting to false?

**Comment by SanderRonde** [comment]
Hey seeing as there's no response I'll just be publishing the (I think) fix. Let me know if it does or does not work for you.
