### ISSUE TITLE
Extension not working due to a warning

### ISSUE THREAD

**Issue by YoungMind1** [SanderRonde/phpstan-vscode#19]
From [PHPStan 1.9](https://github.com/phpstan/phpstan/releases/tag/1.9.0), PHPStan emits a warning regarding the use Xdebug extension.
This breaks the extension.

Note: The message might change in [future](https://github.com/phpstan/phpstan/pull/8343).

I tried to filter out the lines of phpstan output by `!l.startsWith('!')`, but it didn't work.

**Comment by SanderRonde** [comment]
Is this the same issue as #17 ? There should a fix for it available.

**Comment by YoungMind1** [comment]
Yeap it is fixed now. thank you.
The sad part is the Xdebug note is not just one line.
For some reason it breaks the warning into 3 lines.
So I had to ignore These:
`        ".*The Xdebug PHP extension is active.*",
        ".*slow down performance.*",
        ".*breakpoints.*"`

**Comment by SanderRonde** [comment]
Ah that sucks. Let's hope the warning can be disabled from the Phpstan side soon

**Comment by lmichelin** [comment]
Hello, I found a way to fix this issue by creating an executable file named `phpstan-without-xdebug` in the `bin` folder of my symfony app and containing the following line:

```
XDEBUG_MODE=off vendor/bin/phpstan "$@"
```

then I added the following line in my `settings.json` file in VS Code:

```
"phpstan.binCommand": ["bin/phpstan-without-xdebug"],
```

Hope this can help...
