### ISSUE TITLE
Closing multiple files starts multiple simultaneous checks

### ISSUE THREAD

**Issue by driskell** [SanderRonde/phpstan-vscode#20]
I have a large project and when I finish working on a branch I will close all open files.
This triggers a 10 minute long 100% CPU scan of all those files simultaneously as they close, even though they were unchanged. Activity Monitor shows many many php processes running simultaneously.

**Comment by SanderRonde** [comment]
Ah look like [this line](https://github.com/SanderRonde/phpstan-vscode/blob/master/client/src/lib/documentManager.ts#L125) is responsible for that. Not sure why I made it do a force check on file close. Will fix this soon!

**Comment by SanderRonde** [comment]
Thanks, I'm happy to hear!
