### ISSUE TITLE
Provide usage example for the config key "phpstan.paths"

### ISSUE THREAD

**Issue by joshsedl** [SanderRonde/phpstan-vscode#23]
Currently, there is no proper usage example of the config key "phpstan.paths".

I expected it to be similar to the "paths" phpstan.neon parameter, where paths can be given as an array. But since the default for "phpstan.paths" is an empty json object, I am unsure how to properly use it.

**Comment by SanderRonde** [comment]
Added some usage examples (in both the extension settings and README). It's actually not a set of paths that should be checked, instead it's a path mapping (see explanation in README).

**Comment by joshsedl** [comment]
Thanks a lot! What a quick reply! Awesome 💯
