### ISSUE TITLE
Provide quick fix or autocompletion to ignore errors

### ISSUE THREAD

**Issue by FrankySnow** [SanderRonde/phpstan-vscode#25]
Hi,
when I encounter a PHPStan error that I want to [ignore ](https://phpstan.org/user-guide/ignoring-errors):
![image](https://user-images.githubusercontent.com/22062145/213606230-024caaad-d5ed-4c58-94f9-c0d6e1b1148a.png)
I would like VS Code to add  `// @phpstan-ignore-next-line` or `// @phpstan-ignore-line` for me, but there are "No quick fixes available".

It would be cool if the extension provided such "quick fixes", like ESLint for JS/TS :
![image](https://user-images.githubusercontent.com/22062145/213610915-c774731c-743e-43b3-9555-df980a0b07c2.png)

Similarly, the extension could provide an autocompletion like Phan :
![image](https://user-images.githubusercontent.com/22062145/213609712-4b364e7d-f13f-41e2-accd-c4dcfd649ec5.png)

Thanks in advance for considering this !

**Comment by SanderRonde** [comment]
That's actually a very good idea! Will implement this when I've got the time. Thanks for the suggestion.
