### ISSUE TITLE
XDebug breaks the extension

### ISSUE THREAD

**Issue by MissaelAnda** [SanderRonde/phpstan-vscode#26]
Apparently the XDebug warning message breaks the extension, always throws error.

![image](https://user-images.githubusercontent.com/31199350/214153778-16cbdd9b-0ce7-41e5-9ebb-ea0406904416.png)

![image](https://user-images.githubusercontent.com/31199350/214153678-bdfa2aff-0463-4a96-a26b-10924f08c154.png)

**Comment by SanderRonde** [comment]
Looks like this is the same one as [this issue](https://github.com/SanderRonde/phpstan-vscode/issues/19) and [the one it references](https://github.com/SanderRonde/phpstan-vscode/issues/17) right?

**Comment by MissaelAnda** [comment]
Yes it is.

**Comment by SanderRonde** [comment]
Alright it should be fixable through the same methods used in those issues then. Closing this one for now.

**Comment by hugoburguete** [comment]
I wasn't able to resolve this issue with regex (tbh, im not very good at regex :D) but found an alternative instead so if anyone in the future is experiencing this, you can turn off xdebug by passing the `--xdebug` flag to phpstan. 

So in the extension options -> `PHPStan Options` -> Add Item -> and add `--xdebug` should resolve the issue.

You may have to restart VSCode.

**Comment by MissaelAnda** [comment]
I just added `XDebug: .*` and `! .*` to `phpstan.ignoreErrors` and it works fine.

**Comment by zh7k0** [comment]
For future people looking at this: `--xdebug` doesn't turn off xdebug, it turns it on.
source: [https://phpstan.org/user-guide/command-line-usage#--xdebug](https://phpstan.org/user-guide/command-line-usage#--xdebug)

**Comment by hugoburguete** [comment]
> For future people looking at this: `--xdebug` doesn't turn off xdebug, it turns it on. source: https://phpstan.org/user-guide/command-line-usage#--xdebug

This is correct. I forgot to update my comment above so thanks for doing it for me :)

MissaelAnda's solution looks like the way to go (although I haven't tested it myself)

**Comment by ljubadr** [comment]
Those notifications can be disabled by changing [xdebug.log_level](https://xdebug.org/docs/all_settings#log_level) 

I always use `xdebug.log_level=0` to turn off everything except critical errors
