### ISSUE TITLE
Using phpstan with Dev Containers extension - timeout issue

### ISSUE THREAD

**Issue by ultimike** [SanderRonde/phpstan-vscode#32]
Hello,

I'm trying to use this extension with the Dev Containers extension. 

I'm using a similar extension (PHP Sniffer & Beautifier) with Dev Containers and it is working fine, and I can't figure out what I'm missing to get this extension to work.

Here's my config:

```
    /* phpstan */
    "phpstan.enabled": true,
    "phpstan.showProgress": true,
    "phpstan.binPath": "/app/vendor/bin/phpstan",
    "phpstan.configFile": "/app/phpstan.neon",
```

And my /app/phpstan.neon file:

```
parameters:
  level: 6
  paths:
    - modules
```

The error I get is: `PHPStan check timed out after 10000ms`

I've tried it with and without the `paths` parameter in my phpstan.neon and I've also tried using `phpstan.binCommand` instead of `phpstan.binPath` - with no improvement. 

Here's my settings for PHP Sniffer & Beautifier (this works):

```
    /* PHP Sniffer & Beautifier */
    "phpsab.executablePathCS": "/app/vendor/bin/phpcs",
    "phpsab.executablePathCBF": "/app/vendor/bin/phpcbf",
    "phpsab.standard": "/app/phpcs.xml",
```

What am I missing?

thanks,
-mike

**Comment by SanderRonde** [comment]
Could it really be timing out? What if you increase the max timeout time? And what happens when you run the same command in a terminal?

**Comment by ultimike** [comment]
Ugh - I just tried it again today and it works. 

I had a similar issue with running PhpUnit tests - not sure what the issue was yesterday, but things appear to be working today.

Sorry for the false alarm!

-mike

**Comment by SanderRonde** [comment]
Good to hear!
