### ISSUE TITLE
Extension Settings is named wrong

### ISSUE THREAD

**Issue by finn-matti** [SanderRonde/phpstan-vscode#33]
![Screenshot 2023-05-04 at 10 53 30](https://user-images.githubusercontent.com/56148301/236143334-991eb3ca-c378-49b9-afa0-aac38e354a33.png)

For some reason the extension settings for phpstan-vscode are named incorrectly.

EDIT: For clarification it should be called something like "phpstan".

**Comment by SanderRonde** [comment]
Hmm do you mean this setting should just be called "phpstan"? I think a name like that is fine when it's just "/usr/bin/phpstan" but in cases where it's more complex (such as when ran in a docker container) a name like "binpath" is more fitting. What do you think?

**Comment by finn-matti** [comment]
Sorry, for being unclear. Take a look at the sidebar:

![Screenshot 2023-05-05 at 10 04 39](https://user-images.githubusercontent.com/56148301/236395985-0a9fdb27-2c7f-4ba4-b393-3dd53727105d.png)

You would never guess that "Extension Configuration" is the config for the phpstan extension. It needs to be less generic.

**Comment by SanderRonde** [comment]
Ah yeah you're right. Weird, will take a look!
