### ISSUE TITLE
Version 2.2.25 is broken

### ISSUE THREAD

**Issue by ErnstStavroBlofeld** [SanderRonde/phpstan-vscode#34]
Version 2.2.25 published on 23-06-2023 is invalid.
Several files are missing from `~/.vscode/sanderronde.phpstan-vscode-2.2.25`

```sh
~ ls ~/.vscode/extensions/sanderronde.phpstan-vscode-2.2.25
package.json

~ ls ~/.vscode/extensions/sanderronde.phpstan-vscode-2.2.24
CHANGELOG.md  LICENSE.txt  out  package.json  php  README.md  reported.json  static
```

Extension crashes at startup.

**Comment by SanderRonde** [comment]
Are you sure? Can you try re-installing the extension? It works for me and downloading the `vsix` file [from the marketplace](https://marketplace.visualstudio.com/items?itemName=SanderRonde.phpstan-vscode) also shows that it contains the required files.

**Comment by ErnstStavroBlofeld** [comment]
I did try reinstalling extension several times, restarting vscode between each install, but I've gotten the same error every time. Now i tried manually removing 2.2.25 folder and reinstalling, and it worked, so i guess it was some kind of vscode bug. Sorry for wasting your time.

**Comment by SanderRonde** [comment]
Ah weird, glad you found out. No problem!
