### ISSUE TITLE
Extension not working on Windows

### ISSUE THREAD

**Issue by Blasio** [SanderRonde/phpstan-vscode#4]
Extension is not working in VSCode on Windows.  PHPStan is started and reports issues found during analysis, but extension log shows no errors.  At a guess issue is caused by the split on colon in OutputParser since PHPStan output on windows will include a colon in the file path which the parser does not seem to cater for.

E.g.
C:\Projects\WebApp\view1_DoAction.php:95:Variable $genericError might not be defined.

**Comment by SanderRonde** [comment]
Thanks for the bug report!
