### ISSUE TITLE
Paths excluded in `phpstan.neon` `parameters.excludePaths` throw an error on save

### ISSUE THREAD

**Issue by fritz-c** [SanderRonde/phpstan-vscode#41]
I have a `phpstan.neon` config file that looks more or less like the following:

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app
    level: 5
    excludePaths:
        - ./tests/*
```

and my VSCode config contains the following:

```json
"phpstan.binCommand": [
    "docker-compose",
    "exec",
    "app",
    "vendor/bin/phpstan"
],
"phpstan.enableLanguageServer": false,
"phpstan.paths": {
    "/path/to/my-project": "/app"
}
```

The extension works perfectly for almost all files, but when I edit a file under `tests/`, I get the following error in the console, and a VSCode notification pops up:

```
[check:160] Spawning PHPStan with the following configuration:  {"binCmd":"docker-compose","args":["exec","app","vendor/bin/phpstan","analyse","-c","/app/phpstan.neon","--error-format=raw","--no-interaction","--memory-limit=1G","--no-progress","/app/tests/Feature/MyFeatureTest.php"]}
[check:160] PHPStan process exited with error  filteredErr=! [NOTE] No files found to analyse.
[WARNING] This will cause a non-zero exit code in PHPStan 2.0.  rawErr=
 ! [NOTE] No files found to analyse.                                            

 [WARNING] This will cause a non-zero exit code in PHPStan 2.0.                 

  data=
[check:160] Check completed for file:///path/to/my-project/tests/Feature/MyFeatureTest.php errors= {}
```
<img width="463" alt="image" src="https://github.com/SanderRonde/phpstan-vscode/assets/4413963/24e6ffd9-0f6d-47b0-a30a-d7f38b1ef83f">

It appears that the `phpstan.neon` config is being read in properly, but calling phpstan with a file it has explicitly been told to ignore results in 0 files being checked and that results in an error.

**Comment by SanderRonde** [comment]
Is this unexpected behavior? From [this comment](https://github.com/phpstan/phpstan/issues/9410) by the creator of PHPStan it appears to be intentional.

**Comment by fritz-c** [comment]
I believe it is the expected behavior for phpstan. Using that configuration in combination with your extension, however, I couldn't find any way to avoid the repeated appearance of the error notification when I had the extension configured to lint the current file every time I save.

**Comment by SanderRonde** [comment]
Ah never mind this is indeed the fault of the extension. It's triggering checks on files that it shouldn't check. Will fix when I've got some time.

**Comment by fritz-c** [comment]
Sounds good, thanks for looking into it.

I figured out a fix for myself in the meantime, of using `path` properties on `ignoreErrors` entries in the `phpstan.neon` file instead of `excludePaths`.

**Comment by SanderRonde** [comment]
I think I got a fix for this issue. Would you mind testing it for me? I've attached the `.vsix` (VSCode extension installer) file as a `.zip` file since github doesn't allow uploading of `.vsix` files. Could you:
- Download it
- Rename it to `.zip`
- Install it in VSCode by going to "extensions", hitting the dots and clicking "install from VSIX"

Thanks in advance!

[phpstan-vscode-2.2.24.zip](https://github.com/SanderRonde/phpstan-vscode/files/12795727/phpstan-vscode-2.2.24.zip)

**Comment by SanderRonde** [comment]
Looked into this some more, this should be automatically fixed when moving to project-wide checking. That is currently active in the pre-release version of the extension.
