### ISSUE TITLE
Output errors are garbled.

### ISSUE THREAD

**Issue by TR0205** [SanderRonde/phpstan-vscode#42]
When I tried to use this extension, an error message "PHPStan: process exited with error, see log for details" appeared in the lower right corner.

![image](https://github.com/SanderRonde/phpstan-vscode/assets/65379809/2d2d360d-80c5-4ed2-92cf-4d1d68610609)

I tried to check the output to see what kind of error is being output, but the text is garbled and I cannot see it.

I am Japanese, is this affecting me in any way?

Environment
OS:Windows10

```
[check:23] Check started for file:///c%3A/Users/projects/app/Http/Controllers/BaseController.php
[check:23] Spawning PHPStan with the following configuration:  {"binCmd":"c:\\Users\\projects\\application\\vendor\\bin\\phpstan","args":["analyse","-c","c:\\Users\\projects\\application\\phpstan.neon","--error-format=raw","--no-interaction","--memory-limit=1G","--no-progress","c:\\Users\\projects\\application\\app\\Http\\Controllers\\BaseController.php","-a","C:\\Users\\AppData\\Local\\Temp\\tmp-2292-8mxAFY219JoZ\\autoload.php","-c","C:\\Users\\AppData\\Local\\Temp\\tmp-2292-8mxAFY219JoZ\\config.neon"]}
[check:23] PHPStan process exited with error  filteredErr='c:\Users\projects\application\vendor\bin\phpstan' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B  rawErr='c:\Users\projects\application\vendor\bin\phpstan' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
  data=
[check:23] Check completed for file:///c%3A/Users/projects/app/Http/Controllers/Cdnext/BaseController.php errors= {}
```

**Comment by SanderRonde** [comment]
Ah strange, it could be that this is happening because you're using japanese. What happens when you run the command shown in your terminal yourself? Does it also show garbled text, does it show japanese or english? I'm guessing this is some string-encoding issue.
