### ISSUE TITLE
"PHPStan: process exited with error, see log for details" - Where is the log file?

### ISSUE THREAD

**Issue by Nick-Hope** [SanderRonde/phpstan-vscode#46]
I'm trying to set phpstan up in DDEV on WSL2 (Ubuntu).

When I open a php file I get "PHPStan: process exited with error, see log for details" at the bottom right.

Where is the log file? I can't find it.

My workspace settings.json includes these lines related to phpstan:

```
"phpstan.binPath": "/home/nick/sites/bv/vendor/bin/phpstan",
"phpstan.configFile": "/home/nick/sites/bv/phpstan.neon",
"phpstan.enabled": true, 
"phpstan.showProgress": true
```

**Comment by SanderRonde** [comment]
In VSCode there is a panel at the bottom called "output" (alongside "terminal" and "problems"). In that panel, select "phpstan" in the top-right dropdown. For future reference, that's where you'll find all extension logs.

Will close the issue for now, if you can't make sense of the logs feel free to reply again.

**Comment by Nick-Hope** [comment]
Thank you very much @SanderRonde. It turns out that my error was because of "Invalid combination of tabs and spaces" in phpstan.neon, which I have now fixed. Happy New Year!

**Comment by SanderRonde** [comment]
Ah that makes sense. Thanks and you too!
