### ISSUE TITLE
docker howto

### ISSUE THREAD

**Issue by quazardous** [SanderRonde/phpstan-vscode#53]
Hi,

I would like to ask you on the right way to use the plugin with a dockerized phpstan stack.

the main issue is how to map the path between vscode and the container.

Before I start diving into it, could you provide me some pointers ?

thx

**Comment by quazardous** [comment]
just read the doc doo

**Comment by quazardous** [comment]
but it does not work because of docker verbose output...

```bash
17:02 $ bin/phpstan_docker 
[+] Creating 1/0
 ✔ Container xxx-mariadb-1  Running                                                                                                      0.0s 
Note: Using configuration file /var/www/xxx/phpstan.neon.
```

vscode output
```
[check:18] PHPStan process exited with error  filteredErr=Container m2m-mariadb-1  Running  rawErr= Container m2m-mariadb-1  Running


  data=
[status-bar] Hiding status bar, last operation result = Error
```

**Comment by quazardous** [comment]
And do you happen to know how to tell phpstan@docker to use cache ?

**Comment by SanderRonde** [comment]
Is there not some way to prevent that output while running the docker phpstan command? If not then it's going to be pretty hard to work around this. I'd have make the phpstan command specifically ignore docker-related output but not the rest.
