### ISSUE TITLE
PHPStan Cache Not Utilized in v3.0.1 on Mac with PHP 8.3

### ISSUE THREAD

**Issue by philipkozeny** [SanderRonde/phpstan-vscode#57]
First of all: Thanks for the great plugin!

I've encountered an issue with PHPStan cache not being utilized while running version 3.0.1 on a Mac with PHP 8.3. It seems that every file is rechecked upon saving, leading to significant cpu spikes. This behavior is also seen at the progress bar, which indicates that all files undergo checking on each save.

When executing `vendor/bin/phpstan` directly from the terminal, the cache is recognized and used, resulting in a much faster process.

Could you advise on any additional information or logs that would be helpful for diagnosing this issue?

Thanks for your help.

**Comment by SanderRonde** [comment]
Hey thanks for the report. Could you do the following for me?
- Share the logs of the extension when the issue occurs. They're shown in the `Output` panel under `PHPStan Client`. Ideally running it a couple of times.
- Look for the line "Spawning PHPStan with the following configuration" and run the shown command in your terminal. Can you check whether the issue then still occurs, or if some warning of some sort is outputted?

Thanks!

**Comment by gglnx** [comment]
I've got the same problem (but with PHP 8.1 on a M2 mac). The log:

```
[check:42] Check started for project
[status-bar] Showing status bar
[file-watcher] Document changed, triggering
[check:43] Check started for project
[fixer-manager] No file changes, not checking
[check:42] Check completed for project, errors= {"fileSpecificErrors":{},"notFileSpecificErrors":[]}
[check:43] Spawning PHPStan with the following configuration:  {"binStr":"/[redacted]/vendor/bin/phpstan","args":["analyse","-c","/[redacted]/phpstan.neon","--error-format=json","--no-interaction","--memory-limit=1G","-a","/[redacted]/.vscode/extensions/sanderronde.phpstan-vscode-3.0.3/_config/autoload.php","-c","/[redacted]/.vscode/extensions/sanderronde.phpstan-vscode-3.0.3/_config/config.neon"]}
[process-spawner] Spawning process 86896 with timeout 900000
```

The output:

```
$ vendor/bin/phpstan analyse -c /[redacted]/phpstan.neon --error-format=json --no-interaction --memory-limit=1G -a /[redacted]/.vscode/extensions/sanderronde.phpstan-vscode-3.0.3/_config/autoload.php -c /[redacted]/.vscode/extensions/sanderronde.phpstan-vscode-3.0.3/_config/config.neon
 396/396 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

{"totals":{"errors":1,"file_errors":0},"files":[],"errors":["<error>Child process error</error> (exit code 1): Error: Unable to encode JSON: Recursion detected\n"]}%
```

* PHPStan version: 1.10.60
* PHP version: 8.1.23
* Extension version: 3.0.3
* VS Code version: 1.87.1
* OS: macOS 13.6.3 (M2 MacBook Air)

**Comment by SanderRonde** [comment]
Could you try disabling the `phpstan.enableLanguageServer` setting. Does it still occur then?

**Comment by gglnx** [comment]
Without `phpstan.enableLanguageServer` enabled, everything is fast and quick.

**Comment by SanderRonde** [comment]
Ah good to know. Then I guess my recommendation is to disable that option. It only provides on-hover information and is not actually needed for type-checking.

Going further I've disabled that option by default in the pre-release version of the extension so it'll be opt-in instead.

I'll close this issue for now, maybe I'll spend more time getting the hover-provider feature to work without busting the cache on macs but that'll be kind of hard. So for now just "disable that setting" will do.
