### ISSUE TITLE
Error when phpstan.configFile is empty

### ISSUE THREAD

**Issue by MrMeshok** [SanderRonde/phpstan-vscode#62]
In the description, it states "Path to the config file (**leave empty to disable**, use a comma-separated list to resolve in order)".
But when I set it to an empty string in the output, I see
```
[check:8] Check started for project
[status-bar] Showing status bar
[status-bar] Hiding status bar, last operation result = Error
[check:8] Check completed for project, errors= {"fileSpecificErrors":{},"notFileSpecificErrors":[]}
```
I use version 3.0.3 with docker

**Comment by SanderRonde** [comment]
Ah yeah not sure why I put that there, running without a config file is not really possible I think. I'll update the description. Or is there any other behavior you'd expect?

**Comment by MrMeshok** [comment]
I kinda expected [default resolution priority](https://phpstan.org/config-reference#config-file), so not including `-c` option in command.
For now, I just set my configFile to `phpstan.neon,phpstan.neon.dist,phpstan.dist.neon`

**Comment by SanderRonde** [comment]
Hmm when using an empty string it'll just use the empty string, when not changing the setting at all it'll use the default of `phpstan.neon`. I agree though that the resolution priority you linked is a more sensible default so I'll update it to that.

**Comment by MrMeshok** [comment]
If you omit `-c` option altogether phpstan will resolve it.
But it does write in output
>Note: Using configuration file /var/www/html/phpstan.neon.
Maybe this mess up your parsing of output

**Comment by SanderRonde** [comment]
It shouldn't affect the parsing of output, but good to know
