### ISSUE TITLE
"Not checking project because of invalid PHP file" with PHP 8.3 Typed Class Constants

### ISSUE THREAD

**Issue by MrMeshok** [SanderRonde/phpstan-vscode#63]
Сan be checked with this example
```php
class Test
{
    public const string TEST = 'test';
}
```
I understand that you use library php-parser for checking and can't do much until library will be updated. Maybe add option to disable this check, because phpstan can check php syntax himself.
I deleted line 
``let e=this._config.documents.getInvalidFile();if(e){se(this._config.connection,bo,`Not checking project because of invalid PHP file: ${e}`);return}``

from ~/.vscode/extensions/sanderronde.phpstan-vscode-3.0.3/out/server.js, everything seems ok

**Comment by SanderRonde** [comment]
Ahh you're right. I'll make this a setting so you can turn it off.

**Comment by MrMeshok** [comment]
Thank you!

**Comment by SanderRonde** [comment]
I've added the `phpstan.checkValidity` setting in the latest `3.0.4` version release
