### ISSUE TITLE
Opening files with errors in anonymous classes fail

### ISSUE THREAD

**Issue by steffans** [SanderRonde/phpstan-vscode#64]
Clicking on errors in anonymous classes will fail to open the file in the editor, because the file can not be found.

Here is an example test.php, set phpstan to level 6
```
<?php

return new class {
    protected array $foo = ['a', 'b', 'c'];
};
```

Click on the error to open it

<img width="613" alt="Bildschirmfoto 2024-03-20 um 07 36 48" src="https://github.com/SanderRonde/phpstan-vscode/assets/321013/24cdaef4-ac48-46b5-980a-045ec6675363">

**Comment by SanderRonde** [comment]
Thanks for the report. Can you check out the pre-release version and see if the issue is still present there? I can't seem to replicate it there.
