### ISSUE TITLE
No error highlight in traits

### ISSUE THREAD

**Issue by MrMeshok** [SanderRonde/phpstan-vscode#65]
Take this file for example
```PHP
Trait TestTrait
{
    public function getFromNullable(?stdClass $stdClass): mixed
    {
        return $stdClass->foo;
    }
}

class FirstClass
{
    use TestTrait;
}

class SecondClass
{
    use TestTrait;

    public function getFromNullableClass(?stdClass $stdClass): mixed
    {
        return $stdClass->foo;
    }
}
```
In VS Code I see this
![image](https://github.com/SanderRonde/phpstan-vscode/assets/72924086/4b65a7f8-0549-40b7-9f18-9de7a28d0a13)

But if i run phpstan in terminal
![image](https://github.com/SanderRonde/phpstan-vscode/assets/72924086/658f4b69-7204-4116-9fcc-e3df2016250c)

I also found this blog about traits
[https://phpstan.org/blog/how-phpstan-analyses-traits](https://phpstan.org/blog/how-phpstan-analyses-traits)

**Comment by SanderRonde** [comment]
Thanks for the report! (You're on a roll :))

I've got some good news and some bad news:
- I can fix the issue of not showing the error at all in the file, and the issue of it being shown in a nonexistent file in the `Problems` viewer
- I can't actually display the error on the line of the class that uses the trait. Instead PHPStan reports it as occurring in the trait "in the context of" the class that uses it. But given that that's the way PHPStan reports it as well I think that might be fine.

**Comment by MrMeshok** [comment]
Awesome! I actually didn't expect to see error in a class that uses the trait. And after reading this blog post it's definitely not needed
