### ISSUE TITLE
The type of variable is not shown when hovering since v3.1.3

### ISSUE THREAD

**Issue by abcang** [SanderRonde/phpstan-vscode#77]
It worked fine until v3.1.2. However, since v3.1.3, it stays in the reading state forever even when hovering.

The output of the PHPStan Language Server was as follows.
```
[file-watcher] Checking: Hover action
```

I am using Single File Mode and have not tested the behavior when Single File Mode is disabled.

**Comment by lkrms** [comment]
I can confirm the behaviour is the same with Single File Mode disabled. Downgrading to v3.1.2 restores PHPStan output on hover immediately.

(And I have to say, this is a killer feature! Thank you so much for your work on this excellent extension, @SanderRonde 🙏🏻)

**Comment by SanderRonde** [comment]
Thanks for the report, found the issue and fixed it :) Should be live in version `3.1.6` in a few mins
