### ISSUE TITLE
VS Code not retaining error information when viewing files

### ISSUE THREAD

**Issue by SC-Elizabeth** [SanderRonde/phpstan-vscode#79]
Steps:

1. I see the extension checking the project at the bottom right.
2. When it finishes checking it populate the problem tab on the terminal window with all the error and highlights all the files with issues in the explorer pane.
3. The moment I click on a problem/file the errors for disappear from both the problem tab and explorer pane and nothing at all shows up in the file.

Notes:
- The error logs for VS Code and the extension don't have any errors.
- Other extensions don't have this problem.

**Comment by SC-Elizabeth** [comment]
Apparently i can still see the errors in a file if the entirety of the scan is done while i'm looking at that file. All other problems in other files are still inaccessible though.

**Comment by SanderRonde** [comment]
Hi thanks for the report. Is there anything special about your setup that might be influencing this? Maybe you're running in WSL, docker or something like that? Can you tell me a bit more about it so I can maybe reproduce it? 

And, just to be sure, with "The error logs for VS Code and the extension don't have any errors" do you mean it doesn't list any PHPStan errors or no "the check has failed" errors?

**Comment by SC-Elizabeth** [comment]
Hey, thanks for the response!

My setup has PHPStan running on another windows machine that I'm connecting to via network drive which certainly could be a unique setup.

And i apologize, I mean to say that PHPStan appears to be logging errors in the extension log directly, but i don't see any indication of errors that would suggest the extension isn't working.

**Comment by SanderRonde** [comment]
Ah interesting. I'll try and replicate this setup to try and debug it. Where does your source code live? Also on the network drive or does it live on the local machine?

**Comment by SC-Elizabeth** [comment]
Also on the network drive. Thanks for looking into it!

**Comment by SanderRonde** [comment]
I did some investigating, turns out this wasn't broken specifically on network drives but for windows in general... But it should be fixed in the newest version (3.1.9) which I've just published.
