### ISSUE TITLE
Place `@phpstan-ignore` inside existing docblocks

### ISSUE THREAD

**Issue by jrmajor** [SanderRonde/phpstan-vscode#89]
If there is a docblock above a problematic line, I would like the “ignore PHPStan error” fix to place the `@phpstan-ignore` directive inside the docblock, instead of creating a new comment.

Example:
```php
class Siblings extends Relation
{
    /** @var Person */
    protected $parent; // error on this line
}
```
Current fix:
```php
class Siblings extends Relation
{
    /** @var Person */
    // @phpstan-ignore-next-line
    protected $parent; // error on this line
}
```
Expected fix:
```php
class Siblings extends Relation
{
    /**
     * @var Person
     * @phpstan-ignore-next-line
     */
    protected $parent; // error on this line
}
```
If this is desired, I can tackle this after #88 is merged.

**Comment by SanderRonde** [comment]
I agree that this indeed a very nice feature to have. If you need any help feel free to ask!
