### ISSUE TITLE
Allows to scan for complete directory

### ISSUE THREAD

**Issue by edafonseca** [SanderRonde/phpstan-vscode#9]
Hello,

Is there a way to scan a whole directory to generate "Problems" for all project ?

Thanks

**Comment by SanderRonde** [comment]
That should work fine if your phpstan.neon file includes the directory.

Or do you mean having a dedicated "scan this folder" command like the "scan current file" command?

**Comment by edafonseca** [comment]
This is working great when saving a file, but is it possible to lint all project ? In actions, I only get "Scan current file for errors".

Actually, what I am looking for is to get in Problems tab the list of all project phpstan errors.

Thanks

**Comment by SanderRonde** [comment]
Ah interesting idea. I'll start working on making that possible :)

**Comment by edafonseca** [comment]
Thanks a lot !! :)

**Comment by SanderRonde** [comment]
Done :) should be live in the newest version (

**Comment by edafonseca** [comment]
Awesome ! 

However , here are some errors. When I run "check for project errors" :
- PHPStan scan is timed out depending on this config : "Timeout in milliseconds for a single file check. After this time the checking process is canceled"
- Scan ends with error : "PHPStan: process exited with error, see log for details"
- In logs, I get 
```
[exthost] [warning] [SanderRonde.phpstan-vscode] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[sql]', provide the URI of a resource or 'null' for any resource.
```

Am I missing something ?

Thanks

**Comment by SanderRonde** [comment]
Ah looks like stuff is a bit broken then, will unpublish it while I investigate

**Comment by SanderRonde** [comment]
I just published a pre-release version of the extension where I re-introduced the changes (this time I'm pretty sure I fixed the bugs). Could you give it a test and let me know if it works? Just click on the extension in your extensions sidebar and on the detail-page click on "Switch to Pre-Release Version".

**Comment by edafonseca** [comment]
Awesome ! You now have the best phpstan extension on vscode 😍.

I have tried the 2.2.2 version, all good until now. I will keep going with it and let you know if I see some problems.

Thanks again :)

**Comment by SanderRonde** [comment]
Thanks for the kind words! Good to hear it all works, I'll publish it to the non-pre-release channel then.
